Improve floating point comparisons with zero
slint-ui/slint pull request #1156
Opened 2022-04-07 12:17 UTC by tronical

Use `approx_eq` where applicable and `< 0` for the opacity shortcut.

2022-04-07 12:36 UTC, ogoffart commented on internal/core/items/text.rs
> +                if font_size.approx_eq(&0.0) {
```suggestion
                if font_size <= 0. {
```

negative font-size don't make sense

2022-04-07 12:36 UTC, ogoffart commented on internal/core/items/text.rs
> +                if font_size.approx_eq(&0.0) {
```suggestion
                if font_size <= 0.0 {
```

2022-04-07 12:40 UTC, hunger requested changes

2022-04-07 12:40 UTC, hunger commented on internal/backends/gl/lib.rs
> +        if self.state.last().unwrap().global_alpha < 0. {
```suggestion
        if self.state.last().unwrap().global_alpha < 0.001 {
```

2022-04-07 12:41 UTC, hunger commented on internal/backends/gl/lib.rs
> +        if self.state.last().unwrap().global_alpha < 0. {
`< 0.` is worse than `== 0.`, considering the value is expected to be `>= 0.0` :-)

2022-04-07 12:48 UTC, hunger commented on internal/core/items.rs
> +        if is_clipping && (geometry.width().approx_eq(&0.) || geometry.height().approx_eq(&0.)) {
`width.approx_eq(&0.)` makes more sense here that `width <= 0.`.

2022-04-07 13:49 UTC, tronical commented
Ok, I don't have a strong opinion on `<= 0` vs `approx_eq(&0)`. I do agree that negative values don't make sense though, so semantically I'm fine with `<= 0`.

What variant should I change this code to?

2022-04-07 14:49 UTC, hunger commented
`approx_eq(&0.)` will cover small positive values. So if you get very close to 0.0 from the positive side, then that is covered by appox_eq, while `<=0.` will not include those.

If you want to cover values that are 0.0 (with rounding error) and negative, then you need to do `<= 0. + EPSILON` where EPSILON is a small enough value. We can be pretty inexact here: Even 0.0001  is close enough to 0 in our use-case to not be noticeable!

2022-04-13 14:45 UTC, tronical commented
Down-prioritizing this (somebody else may beat me to it ;-)

2022-04-13 14:45 UTC, closed without merging