x86_64 linux docker build
slint-ui/slint pull request #1198
Opened 2022-04-27 20:40 UTC by a1ecbr0wn

2022-04-27 20:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slint-ui/slint?pullRequest=1198) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slint-ui/slint?pullRequest=1198) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slint-ui/slint?pullRequest=1198) it.</sub>

2022-04-28 07:22 UTC, ogoffart commented
Thanks for the PR!

I'm going to leave this to @tronical to review because he made the previous images.

I'm slightly concerned about bitrot since we do not test this. But maybe we could add one build for it in .github/workflows/embedded_build.yaml

2022-04-28 09:25 UTC, tronical requested changes
Looks overall good to me - Thanks! I think it makes sense to have this. I think a little fix is needed for the license/copyright checker.

I agree with Olivier, it would be great if `embedded_build.yaml` could be extended to also use this - at least for CI purposes. But I can also do that.

2022-04-28 09:25 UTC, tronical commented on docker/Dockerfile.x86_64-unknown-linux-gnu
> +FROM rustembedded/cross:x86_64-unknown-linux-gnu
I think this should fix the CI error, if you substitute in your name/email :)

```suggestion
# Copyright © your name / your email
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

FROM rustembedded/cross:x86_64-unknown-linux-gnu
```

2022-04-28 09:34 UTC, a1ecbr0wn commented
Sorry, yep, missed that.

2022-04-28 15:31 UTC, a1ecbr0wn commented
Made the changes, hope you are happy with it

2022-04-29 00:17 UTC, tronical approved these changes
Thanks

2022-04-29 00:18 UTC, merged

2022-04-29 07:04 UTC, ogoffart commented
I tried to run ci with this image, and the build failed when trying to build the servo-fontconfig-sys crates:

https://github.com/slint-ui/slint/runs/6223849592?check_suite_focus=true

```
 thread 'main' panicked at '`"pkg-config" "--libs" "--cflags" "fontconfig" "fontconfig >= 2.11.1"` did not exit successfully: exit status: 1
  error: could not find system library 'fontconfig' required by the 'servo-fontconfig-sys' crate
```

looks like it is missing the fontconfig package.

2022-04-29 07:41 UTC, tronical commented
I think that's just because the container is missing from `Cross.toml`. I'll look into it.

2022-04-29 14:49 UTC, a1ecbr0wn commented
You are right that it is not in the `Cross.toml`, sorry I should have done this do you want me to submit another PR?

2022-04-30 07:32 UTC, tronical commented
No worries, done in 7b0dab4ab1fd49cba37ab4827efe9dd93841d20d :)