Fix compilation of generated Rust code when token stream contains sin…
slint-ui/slint pull request #1348
Opened 2022-06-15 14:30 UTC by tronical

…gle-quoted semicolon

When using glyph embedding, we generate a character map where each code
point is a literal char.  When the font contains a semicolon and we
generate an entry for that, we write ';' and the CodeFormatter would
think the semicolon is the end of a statement and produce a newline.
That breaks the build of the generated code. Instead teach the formatter
also about single-quoted string literals.

2022-06-15 14:42 UTC, ogoffart requested changes

2022-06-15 14:51 UTC, tronical commented
Closing in favour of https://github.com/slint-ui/slint/pull/1347

2022-06-27 07:46 UTC, tronical commented
Since https://github.com/slint-ui/slint/pull/1347 imposes a significantly slow-down of the build, we decided to revert it and I'll get this change in shape instead.

2022-06-28 16:04 UTC, ogoffart approved these changes
i did the changes i was thinking about.

2022-06-28 16:19 UTC, tronical reviewed
Thanks

2022-06-28 16:20 UTC, merged