make "Invalid Unit" error message more friendly
slint-ui/slint pull request #2701
Opened 2023-05-07 22:38 UTC by donbright

While i was using Slint Pad i noticed it said "Invalid Unit" when i typed in em for a unit. I wasnt sure what units were valid. 

This will make the Invalid Unit error message say something like 

```
error: Invalid unit 'em'. Valid units are: %,phx,px,cm,mm,in,pt,rem,s,ms,deg,grad,turn,rad
```
Thanks

2023-05-07 22:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slint-ui/slint?pullRequest=2701) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slint-ui/slint?pullRequest=2701) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slint-ui/slint?pullRequest=2701) it.</sub>

2023-05-08 06:39 UTC, tronical reviewed
I think that's a nice idea! Olivier, what do you think?

2023-05-08 06:39 UTC, tronical commented on internal/compiler/literals.rs
> +            Unit::iter().filter(|x| x.to_string().len() > 0).join(",")
```suggestion
            Unit::iter().filter(|x| x.to_string().len() > 0).join(", ")
```

2023-05-08 06:39 UTC, tronical commented on internal/compiler/literals.rs
> +    let valid_units = Unit::iter().filter(|x| x.to_string().len() > 0).join(",");
```suggestion
    let valid_units = Unit::iter().filter(|x| x.to_string().len() > 0).join(", ");
```

2023-05-08 09:21 UTC, ogoffart approved these changes

2023-05-16 07:44 UTC, ogoffart commented
This now includes another change.  Could you perhaps make another PR for the simple examples? And keep this PR for the Invalid Unit?

If you're not sure how to do it with git, i can also manually merge the invalid unit patch.

2023-05-22 08:35 UTC, tronical commented
@donbright Please see Olivier's [comment](https://github.com/slint-ui/slint/pull/2701#issuecomment-1549164243) and remove the commits that are unrelated. Or if you're not sure, I can also do that for you in a separate branch and merge that.

2023-05-22 08:36 UTC, tronical requested changes
@donbright Please see Olivier's [comment](https://github.com/slint-ui/slint/pull/2701#issuecomment-1549164243) and remove the commits that are unrelated. Or if you're not sure, I can also do that for you in a separate branch and merge that.

2023-06-05 12:16 UTC, ogoffart commented
I've manually merged the first commit in [a255aaf](https://github.com/slint-ui/slint/commit/a255aaf8d40ddbf2ca7d0f00c8d1e0df2ebab63a)

Thanks for your patch

2023-06-05 12:16 UTC, closed without merging