readme.md
slint-ui/slint pull request #4829
Opened 2024-03-12 20:04 UTC by Abhijrathod

updated

2024-03-12 20:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slint-ui/slint?pullRequest=4829) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slint-ui/slint?pullRequest=4829) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slint-ui/slint?pullRequest=4829) it.</sub>

2024-03-12 21:30 UTC, tronical requested changes
Thank you for your contribution. Many of the suggested changes to the README look like a concrete improvement. There are also changes in there that I don't quite understand or that look like typos to me.

2024-03-12 21:30 UTC, tronical commented on .github/workflows/rust.yml
I suggest to skip the commit that adds this file - I believe this is well covered by ci.yaml.

2024-03-12 21:30 UTC, tronical commented on README.md
> +- **Web**: *In Progress*. Slint apps can be compiled into WebAssembly and can run
I think `compile to` is idiomatic, I'd prefer to stay with `to` over `into`.

2024-03-12 21:30 UTC, tronical commented on README.md
> +The UIkeyboard-based a Domain Specific Language that is declarative, easy to use,
This looks like an unintentional change?

2024-03-12 21:30 UTC, tronical commented on README.md
> +```saint
This also looks like a typo?

2024-03-12 21:30 UTC, tronical commented on README.md
> +Refer to the README of each language directory in the `API` folder:
I think the lower-case spelling is correct as here `api` refers to a folder name, not the abbreviation.

2024-03-12 21:30 UTC, tronical commented on README.md
> +The `Image` element is always on top of another `Image` in the same location.
That looks wrong to me, the "`Image` element ..." part is part of an entire sentence.

2024-03-12 21:30 UTC, tronical commented on README.md
> +using Qt's QStyle to achieve nativnative-lookingets.
This looks like a typo?

2024-03-12 21:30 UTC, tronical commented on README.md
> +- A [**LSP Server**](./tools/lsp) LSPt adds features like auto-complete and live
This also looks like a mistake?

2024-03-12 21:30 UTC, tronical commented on README.md
> +interfaces fun for everyone: from JavaScript, C++, or Rust developers to UI/UX designers. We believe that software grows organically and keeping
Why did you remove the "all the way" part?

2024-03-12 21:30 UTC, tronical commented on README.md
> +We chat in [our Mattermost instance](https://chat.slint.dev) Welcome  are
What is the reason for this change?

2024-03-14 09:14 UTC, ogoffart commented
Thanks for the pull request, but i'm going to close this.
Half of the changes are bogus.

2024-03-14 09:14 UTC, closed without merging