Make it possible to use slint-esp with displays that expect little endian ordered RGB565 pixels
slint-ui/slint pull request #5344
Opened 2024-06-04 10:16 UTC by tronical

We can't automatically determine what the display supports, so we need to make this an opt-in - just like it is with LVGL.

2024-06-04 10:31 UTC, ogoffart approved these changes
:+1: to add an overload with a SlintPlatformConfiguration

Does that mean we should also deprecate the other overloads?
(in particular, the experimental ones could be removed)

2024-06-04 10:36 UTC, ogoffart requested changes
I approved too fast.
Request changes to make byte swapping configurable also in line by line and double buffering modes.

2024-06-04 10:36 UTC, ogoffart commented on api/cpp/esp-idf/slint/include/slint-esp.h
> + *                           render into it, and send it to the display.
We need to remove the experimental gating of the line-by-line though.

Also we need to support byte swap there too.

2024-06-04 10:36 UTC, ogoffart commented on api/cpp/esp-idf/slint/src/slint-esp.cpp
> +                                        .buffer2 = buffer2
When double buffering is enabled, we should set the byte swapping to false to keep compatibility.  And byte swapping should also be implemented there.

2024-06-04 13:37 UTC, tronical commented
The more I think about it, the more I prefer https://github.com/slint-ui/slint/pull/5350 for being faster (it being a compile-time decision) and mirroring the status quo from LVGL.

2024-06-11 07:16 UTC, ogoffart approved these changes

2024-06-11 07:16 UTC, ogoffart commented on api/cpp/esp-idf/slint/src/slint-esp.cpp
>                      slint::platform::SoftwareRenderer::RenderingRotation rotation)
I wonder if we should remove the rotation in there since it was experimental only, and only have the rotation in the "complex" overload

2024-06-11 07:16 UTC, ogoffart commented on api/cpp/esp-idf/slint/include/slint-esp.h
> +void slint_esp_init(SlintPlatformConfiguration config);
Should it perhaps be 

```
void slint_esp_init(const SlintPlatformConfiguration &config);
```

2024-06-11 09:30 UTC, merged