Fix error cursor_rect when text is empty
slint-ui/slint pull request #6006
Opened 2024-08-29 16:34 UTC by Horbin-Magician

When using femtovg, a empty textedit will get a error cursor_rect (with default value). This will result in the input box not being in the correct position when typing Chinese.

I'm trying to fix this problem.
Since I'm not familiar with the code, this change needs to be checked carefully.

2024-08-30 06:59 UTC, tronical commented
Looks good at first glance. I'll give this a try locally today.

2024-08-30 11:53 UTC, tronical commented
Ok, I can reproduce the issue. This happens in particular when the `TextInput` has an alignment set.

2024-08-30 11:59 UTC, tronical commented
Trivial test case:

```slint
export component Test inherits Window {
    width: 300px;
    height: 300px;
    TextInput {
        y: 100px;
        horizontal-alignment: center;
    }
}
```

The IME rect will not be where the cursor is rendered. The cursor location is correct, but that's because the rendering code specifically knows how to deal with the empty string situation.

2024-08-30 12:20 UTC, tronical requested changes
I think this is not quite correct. See also the comment inline. One side-effect of this patch is that the cursor in my test case disappears :-).

I suggest to solve this differently:

In `draw_text_input` you can see this code:

```rust
if let Some(cursor_point) = cursor_point.or_else(|| {
            cursor_visible.then(|| {
                let x = match text_input.horizontal_alignment() {
                    TextHorizontalAlignment::Left => PhysicalLength::default(),
                    TextHorizontalAlignment::Center => width / 2.,
                    TextHorizontalAlignment::Right => width,
                };
                PhysicalPoint::from_lengths(x, next_y)
            })
        }) {
            ...
        }
```

`cursor_point` is an `Option<Point>`, and it'll be `None` if the layout callback was never invoked, because the text is empty. _This_ is where the alignment is taken into account and then the cursor is rendered at the correct position.

One option is to duplicate this logic/approach inside `text_input_cursor_rect_for_byte_offset` and change `result` similarly to be an `Option`.

A perhaps cleaner solution would be to move this fallback handling straight into `layout_text_lines` and make the function return the cursor position instead. That'll also require moving the logic for determining the position that's duplicated between `text_input_cursor_rect_for_byte_offset` and `draw_text_input` into `layout_text_lines` (but take the `draw_text_input` variant).

Does this make sense to you?

If it's unclear to you let me know, I can also give it a short and make a PR.

2024-08-30 12:20 UTC, tronical commented on internal/renderers/femtovg/fonts.rs
> +    'lines: while start <= string.len() && y + font_height <= max_height {
This has the effect that for an empty string, the loop will continue at `start == 0` until `y + font_height <= max_height`. In the given test case that's when y is just under 600. That's not right. I think it's correct that the loop is _not_ entered.

2024-08-30 15:42 UTC, Horbin-Magician commented
I understand what you mean.
But correctly modifying it might be more time consuming for me, I hope you can help me with a PR.

2024-09-01 09:42 UTC, tronical commented
Replacing this with https://github.com/slint-ui/slint/pull/6022

2024-09-01 09:42 UTC, closed without merging