lsp: Ignore
slint-ui/slint pull request #6395
Opened 2024-09-30 16:58 UTC by hunger

Since we work on file paths in the compiler but get URLs from the editor, we end up normalizing URLs down to paths.

In #6375 we open a git diff view, which VSCode considers to be `slint` language to highlight it properly. So it will also sends data to the LSP, using `git:/file/path?lots&of&meta&data` as the buffers URL. We normalize that to /file/path and then update that files contents with (parts of) the diff view. Not too surprising: This triggers errors.

The normalization does not happen in the same way in WASM, so slintpad should be immune to the problem.

I considered to just reject "old" versions, but that can go wrong if you open a diff view first and only then the actual file. It will take a couple of changes to the file to be "newer" than the diff and it will be ignored till then.

An alternative is to remember the base URL we mapped into the internal clean URL first and reject any content form other URLs that map to the same internal URL. Again this will fail when you open the diff view first and it won't "auto-fix" itself afterwards. 

So the only possible approach seems to be filtering the  source URL based on its scheme. We use several, so this is not ideal, but the best option I see right now.

Fixes: #6375

2024-09-30 17:16 UTC, ogoffart requested changes
vscode web extension also have different scheme such as `http(s)` or `vscode` depending if its github.dev or vscode.dev. So i think this is wrong to just ignore them.

From your explanation, it seems like they have a `?` so maybe that's what should be ignored? or at least normalized differently.

2024-09-30 17:18 UTC, ogoffart commented
Another idea: normalize file: to a path, but leave other url verbatim as url

2024-10-01 08:03 UTC, hunger commented
All options suck :-(

"Leave URLs verbatin as url" is what we did for a long time (and in fact still do for `builtin`s). That had interesting effects when looking up files relative to sources. "Normal" URLs in a file path do not start with `/`, so they tend to get considered as relative paths, breaking resource lookups.

So we special casing "plain URLs" in the compiler by parsing them and treating them as URLs when looking up resources has the interesting effect that relative path resolution is subtly different for URLs and for files. And don't get me started on WASM: *All* files are relative there. That also leads to broken resource lookups.

That's why I added all those pathutils to the compiler -- to get all the platforms we care for to behave consistently. Unfortunately that change missed some special cases and got partially reverted right after introduction.

2024-10-01 08:18 UTC, hunger commented
We could just make the compiler take URLs and the problem goes away. We'd even get rid of the special casing for `builtins`.

2024-10-01 10:39 UTC, ogoffart commented
> "Leave URLs verbatin as url" is what we did for a long time (and in fact still do for builtins). That had interesting effects when looking up files relative to sources. "Normal" URLs in a file path do not start with /, so they tend to get considered as relative paths, breaking resource lookups.

On the other hand, I believe it is the simpler to continue to do that.
There are not so many location where we resolve relative path, is there. It might be easier to check for the presence of a ":" in addition to find out.
We already have an helper function i_slint_compiler::pathutils::join. 
I'm not seeing the problem keeping URL as is. 

> We could just make the compiler take URLs and the problem goes away. We'd even get rid of the special casing for builtins.

Yes, that would work too.
We could even have a special type such as `SourceFilePath` or `SourceFileName` or something like that.

A few points
 - Path may not be valid UTF-8.  But this was never tried anyway so might be broken probably already.
 - We should still show human readable relative path in error messages. So the path need to stay relative internally. (as opposed to the canonical paths)

2024-10-04 17:15 UTC, ogoffart commented
Just to rephrase, I thin we should workaround the `git:/` bug by either blacklisintg the `git` scheme (instead of whitelist of the other scheme),  or blacklist the urls that have a query (`?`)

2024-10-07 10:23 UTC, hunger commented
I do not think we will get far with blacklisting specific schemes that are known to be broken. There are just too many extensions out there!

I found a list of all the schemes used by VSCode itself and updates the whitelist based on that. Anything not in that list is registered by an extension.

I suspect almost all of those extra schemes will not be relevant to us as VSCode already handles normal files. This means custom schemes registered by extensions will most likely be some interesting way to retrieve files or some non-standard way of displaying file content, e.g. like `git:/` does. Both will not work well with our stand-alone LS as it can not make sense of the contents or has no way to retrieve resources related to the content.

2024-10-07 10:44 UTC, hunger commented
I need to think this through a bit harder... We can only handle file in non-WASM anyway as that is the only thing our LS can read resources for.

I need to double-check the WASM side of things though.

2024-10-07 11:05 UTC, tronical commented
> Just to rephrase, I thin we should workaround the `git:/` bug by either blacklisintg the `git` scheme (instead of whitelist of the other scheme), or blacklist the urls that have a query (`?`)

I think so, too. I'd exclude the `git` scheme. (I'm not concerned about third-party VS code extensions causing issues, at the moment).

> We could just make the compiler take URLs and the problem goes away.

That's increasingly looking like the best solution. I don't know if now's the time to do that or if it's better to add a hack for the `git:/` bug.

2024-10-07 13:04 UTC, hunger commented
The latest iteration makes VSCode stop reporting non-file buffers to our LSP.

That's what VSCode recommends doing for normal LS here: https://code.visualstudio.com/api/references/document-selector. MS argues that the LS will fail to read resources relative to non-file URLs anyway, so don't even try to make them work like that:-)

THe WASM-side is a bit tricky though: We load files through the VSCOde APis there, so we can support more -- and we need to support more URL schemes as e.g. github.dev uses `vscode-vfs`. So whitelist a few more there. The List of possible schemes in the core VSCode can be found here:

https://github.com/microsoft/vscode/blob/main/src/vs/base/common/network.ts

I think the allowlist includes all those that are relevant for us.

Denylisting git is not a proper solution: Any extension can trigger the same bug and there are thousands of those out there. We can never track all of them down.

2024-10-07 16:31 UTC, hunger commented
@ogoffart: Does your request for changes still stand after the implementation has changed completely?

2024-10-07 19:32 UTC, ogoffart commented
I'm still of the opinion that we shouldn't whitelist some known scheme, but use other methods to filter unsupported feature (the use of a query in the url was what i proposed.)

The document you quote says
> If your feature relies on disk access, make sure to use a document selector with the file scheme.

But we do not rely on disk access since we can access url through to wasm interface.

Anyway. In the interest of getting that fixed, I think we can merge this.

2024-10-07 19:32 UTC, ogoffart approved these changes

2024-10-08 08:32 UTC, merged

2024-10-08 08:39 UTC, hunger commented
> But we do not rely on disk access since we can access url through to wasm interface.

Yeap, we are not. That's why we allowlist a whole lot more in WASM. If something ends up missing: We allowlist that, too.

At least we will get bug reports for "XYZ does not bring up the LS" -- which should be fairly actionable.

On the other side we will get "LS sometimes shows wonky data", which is much less actionable and it will be a pain to figure out which of dozens of installed extensions might under some special circumstance open some buffer that VSCode ends up sending to our LS.